services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: checkit
      POSTGRES_USER: checkit
      POSTGRES_PASSWORD: checkit
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U checkit"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_DB: checkit
      DB_USERNAME: checkit
      DB_PASSWORD: checkit
      NODE_ENV: production
    ports:
      - '3000:3000'
    volumes:
      - /opt/assets:/assets
      - ./client/src/assets:/app/client/dist/assets

volumes:
  pgdata:
